namespace: fullstack-app

# =====================
# Ingress Configuration
# =====================
ingress:
  enabled: true
  host: localhost # or your Minikube IP if not using localhost

# =====================
# MySQL Configuration
# =====================
mysql:
  image: mysql:8.0
  rootPassword: password
  database: expense_database
  service:
    port: 3306
    type: ClusterIP

# =====================
# Backend Configuration
# =====================
backend:
  image: niharika412/k8-backend-lab14:latest
  replicas: 2
  port: 2008
  nodePort: 30045
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "500m"
      memory: "256Mi"
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 5
    targetCPUUtilizationPercentage: 50

# =====================
# Frontend Configuration
# =====================
frontend:
  image: niharika412/k8-frontend-lab14:latest
  replicas: 2
  port: 80
  nodePort: 30070
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "500m"
      memory: "256Mi"
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 5
    targetCPUUtilizationPercentage: 50

  # Point frontend to backend service
  apiUrl: "/api"
